# Generated by Django 3.2 on 2022-03-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_detail_name', models.CharField(blank=True, max_length=64, unique=True)),
                ('article', models.ManyToManyField(to='article.Article')),
            ],
        ),
    ]
